language: android
jdk: oraclejdk8

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

android:
  components:
     - tools
     - build-tools-27.0.0
     - platform-tools
     - extra-android-m2repository
     - extra-google-android-support
     - android-27

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew checkstyle assemble testDebug